version: '3'
services:
  splitwise-docker-mysql:
    restart: always
    container_name: splitwise-docker-mysql
    image: mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: splitwise
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: splitwiseuser
      MYSQL_PASSWORD: splitwiseuser
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 30s
      retries: 5
  splitwise-api:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://splitwise-docker-mysql:3306/splitwise
    depends_on:
      - splitwise-docker-mysql